# This function takes blot data and normalizes it by a scaling factor data.frame 
# generated by Blotscale.R. 
#
#
BlotApply <- function(df, scale_df) {
 Emb <- names(df)[-c(1)]
 CellTime <- df[[2]] 
 
 for (i in 1:length(Emb)) {
    df[,Emb[i]] <- df[,Emb[i]]/scale_df[scale_df[,1] %in% Emb[i],2]
     }
 df[[2]] = CellTime
 
 return(df) }