# Script to load functions 

source('~/Nematode_R/DFtimepts.R')
source('~/Nematode_R/Selectcell.R')
source('~/Nematode_R/RepAuxinfo.R')
source('~/Nematode_R/GetParent.R')
source('~/Nematode_R/GetParents.R')
source('~/Nematode_R/ImportSCD.R')
source('~/Nematode_R/Sortblot.R')
source('~/Nematode_R/Sortblot2.R')
source('~/Nematode_R/PlotAllCells.R')
source('~/Nematode_R/Plotcell.R')
source('~/Nematode_R/Blotscale.R')
source('~/Nematode_R/BlotApply.R')
source('~/Nematode_R/Zscale.R')
source("~/Nematode_R/trimmingSCD.R")
source("~/Nematode_R/Cell_Timeline.R")
source("~/Nematode_R/GroupEmb.R")
source("~/Nematode_R/NormView.R")
source('~/Nematode_R/SCDprocess.R')