# Function to group embryos by axis orientation
# input arguments are list of data.frames, and AuxInfo file generated by function RepAuxfiles

GroupEmb <- function(listdf, Aux_info) {
  
  # Generate list of embryos grouped by axis
  # Enter desired axis groupings, "L" will extract all axis entries ending with "L"
  EmbOrientationRL <- c("R", "L") 
  
  EmbAxisList <- list()
  EmbAxisList <- lapply(EmbOrientationRL, function(x) 
  {Aux_info[grep(paste0("^.+",x, "$"), Aux_info$axis), "name"]})
  names(EmbAxisList) <- EmbOrientationRL
  
  # Group SCD data by embryo orientation
  EmbAxisData <- lapply(EmbOrientationRL, function(x)  {
    listdf$SCD_Data[EmbAxisList[[x]]] })
  
  names(EmbAxisData) <- EmbOrientationRL 
  
  return(EmbAxisData)}