# Function to trim empty values and perform initial normalization of data. Input 
# argument is list of data.frames generated by ImportSCD.R
Trimming <- function(list) {


# Specify columns to remove from data


drops <- c()
list[["SCD_Data"]] <- lapply (list[["SCD_Data"]], function(x) {x[,!(names(x) %in% drops)]})
rm(drops)

# Find missing values and assign NA (where no x and y coordinates given | gweight = 0)
list[["SCD_Data"]] <- lapply(list[["SCD_Data"]], function(df) {within(df, blot[x==0 & y==0 | gweight==0] <- NA)})
list[["SCD_Data"]] <- lapply(list[["SCD_Data"]], function(df) {within(df, gweight[x==0 & y==0 | gweight==0] <- NA)})

# Combine all blot data 
list[["SCD_blot"]] <- cbind(list[["SCD_Data"]][[1]][,c(1,2)], as.data.frame(lapply(list[["SCD_Data"]], function(x) {x$blot})))
names(list[["SCD_blot"]]) <- gsub("X", "", names(list[["SCD_blot"]]))

# Generate time column for each cell
library(stringr)
list$SCD_blot$cellTime <- as.numeric(str_split_fixed(list$SCD_blot$cellTime, ":", 2)[,2])

# Generate Z normalization factor
Zcorr <- OptimZ(list$SCD_Data)

# linearly normalizes blot values in each experiment to middle Z plane (Method Z)
list[["NormalizedZ_blot"]] <-  cbind(list[["SCD_blot"]][,c(1,2)], as.data.frame(lapply(list[["SCD_Data"]], function(df) {
  Znorm <- (33-df$zraw)*Zcorr + 1
  df$blot*Znorm})))

return(list) }