# Function to trim empty values and perform initial normalization of data. Input 
# argument is list of data.frames generated by ImportSCD.R
Trimming <- function(list, directory) {

  
# Find missing values and assign NA (where no x and y coordinates given | gweight = 0)
list[["SCD_Data"]] <- lapply(list[["SCD_Data"]], function(df) {within(df, blot[x==0 & y==0 | gweight==0] <- NA)})

# Combine all blot data 
list[["SCD_blot"]] <- cbind(list[["SCD_Data"]][[1]][,c(1,2)], as.data.frame(lapply(list[["SCD_Data"]], function(x) {x$blot})))
names(list[["SCD_blot"]]) <- gsub("X", "", names(list[["SCD_blot"]]))

# Generate annotation file for SCD data with auxillary information for desired worm strain
list$Aux_info <- RepAuxfiles(directory)

# Extract name of reporter
foo <- strsplit(list$Aux_info$name[1], split = "_")[[1]]
list$repID <- foo[grep("([a-z][a-z][a-z].[0-9])", foo)]
list$repID <- gsub("\\.", "-", list$repID)

# Generate time column for each cell
library(stringr)
list$SCD_blot$cellTime <- as.numeric(str_split_fixed(list$SCD_blot$cellTime, ":", 2)[,2])
names(list$SCD_blot)[names(list$SCD_blot) == "cellTime"] <- "Time"

# Reorder columns for correct indexing
list$SCD_blot <- cbind(ID = list$SCD_blot[,2], list$SCD_blot[,-c(2)])


return(list) }